
SELECT      * FROM  PACS31.STUDYINFO   WHERE STUDYID  ='2260610072'  ORDER BY BESPEAKTIME  desc FETCH FIRST 100 ROWS ONLY

SELECT DEPARTMENTCODE ,DEPARTMENTNAME  * FROM PACS31.PACSDEPARTMENT WHERE DEPARTMENTID ='11000005'  FETCH FIRST 1000 ROWS ONLY
SELECT  s.ISBESPEAK,s.SICKBED, s.SICKROOM, s.*  FROM  PACS31.STUDYINFO  s   ORDER BY s.BESPEAKTIME  desc FETCH FIRST 100 ROWS ONLY
SELECT * FROM  PACS31.DEVICETYPEINFO FETCH FIRST 100 ROWS ONLY


SELECT * FROM  PACS31.DEVICETYPEINFO FETCH FIRST 100 ROWS ONLY


SELECT     *  FROM  PACS31.STUDYINFO WHERE       CHECKSERIALNUM ='20120827000031'

SELECT DISTINCT HISPATIENTTYPE FROM  PACS31.PATIENTINFO 
SELECT    * FROM   PACS31.PATIENTINFO  WHERE   HISPATIENTTYPE='3'
SELECT    * FROM   PACS31.PATIENTINFO WHERE  PATIENTNAME ='沈瑶保'

SELECT     * FROM   PACS31.PATIENTINFO WHERE  IDNUMBER ='340211196710280621'

--SELECT * FROM   PACS31.PATIENTINFO  WHERE OPERATETIME IS NOT null  ORDER BY OPERATETIME  desc FETCH FIRST 100 ROWS ONLY  

SELECT IDNUMBER, COUNT(*) AS duplicate_count
FROM PACS31.PATIENTINFO
GROUP BY IDNUMBER
HAVING COUNT(*) > 1;


SELECT STUDYID, COUNT(*) AS duplicate_count
FROM PACS31.STUDYINFO
WHERE ISAVAILABLE =1
GROUP BY STUDYID
HAVING COUNT(*) > 1;

SELECT DEPARTMENTPATIENTID, COUNT(*) AS duplicate_count
FROM PACS31.STUDYINFO
WHERE ISAVAILABLE =1
GROUP BY DEPARTMENTPATIENTID
HAVING COUNT(*) > 1;


SELECT 
    column_name,
    comments
FROM 
    all_col_comments
WHERE 
    owner = 'PACS31'
    AND table_name = 'STUDYINFO'














